<?php
$blocks = [
    'title_only_hero' => [
        'name' => 'title_only_hero',
        'title' => ('Title Only Hero'),
        'description' => ('Title Only Hero section with background select'),
        'render_callback' => 'render_acf_block_callback',
        'category' => 'happen-blocks',
        'icon' => 'block-default',
    ],
    'title_text_block' => [
        'name' => 'title_text_block',
        'title' => ('Title Text '),
        'description' => ('Description'),
        'render_callback' => 'render_acf_block_callback',
        'category' => 'happen-blocks',
        'icon' => 'block-default',
    ],
    'main_title_image' => [
        'name' => 'main_title_image',
        'title' => ('Main Title Image Block'),
        'description' => ('Description'),
        'render_callback' => 'render_acf_block_callback',
        'category' => 'happen-blocks',
        'icon' => 'block-default',
    ],
    'leaders_block' => [
        'name' => 'leaders_block',
        'title' => ('Leaders Block'),
        'description' => ('Leaders Block section'),
        'render_callback' => 'render_acf_block_callback',
        'category' => 'happen-blocks',
        'icon' => 'block-default',
    ],
    'features_block' => [
        'name' => 'features_block',
        'title' => ('Features Block title'),
        'description' => ('Features Block description'),
        'render_callback' => 'render_acf_block_callback',
        'category' => 'happen-blocks',
        'icon' => 'block-default',
    ],
    'eyebrow_text_block' => [
        'name' => 'eyebrow_text_block',
        'title' => ('Eyebrow text block'),
        'description' => ('Eyebrow text description'),
        'render_callback' => 'render_acf_block_callback',
        'category' => 'happen-blocks',
        'icon' => 'block-default',
    ],
    'cols_info_block' => [
        'name' => 'cols_info_block',
        'title' => ('Cols Info Title'),
        'description' => ('Cols Info description'),
        'render_callback' => 'render_acf_block_callback',
        'category' => 'happen-blocks',
        'icon' => 'block-default',
    ],
    'drop_down_faq_block' => [
        'name' => 'drop_down_faq_block',
        'title' => ('Drop down FAQ Title'),
        'description' => ('Drop down FAQ description'),
        'render_callback' => 'render_acf_block_callback',
        'category' => 'happen-blocks',
        'icon' => 'block-default',
    ],
    'eyebrow_video_text_block' => [
        'name' => 'eyebrow_video_text_block',
        'title' => ('Eyebrow Video text block'),
        'description' => ('Eyebrow Video text description'),
        'render_callback' => 'render_acf_block_callback',
        'category' => 'happen-blocks',
        'icon' => 'block-default',
    ],
    'testimonials_block' => [
        'name' => 'testimonials_block',
        'title' => ('Testimonials block'),
        'description' => ('Testimonials description'),
        'render_callback' => 'render_acf_block_callback',
        'category' => 'happen-blocks',
        'icon' => 'block-default',
    ],
    'staggered_cols_info_block' => [
        'name' => 'staggered_cols_info_block',
        'title' => ('Staggered Cols Info Title'),
        'description' => ('Staggered Cols Info description'),
        'render_callback' => 'render_acf_block_callback',
        'category' => 'happen-blocks',
        'icon' => 'block-default',
    ],
    'related_blog_posts_block' => [
        'name' => 'related_blog_posts_block',
        'title' => ('Related Blog Posts Title'),
        'description' => ('Related Blog Posts description'),
        'render_callback' => 'render_acf_block_callback',
        'category' => 'happen-blocks',
        'icon' => 'block-default',
    ],
    'big_features_block' => [
        'name' => 'big_features_block',
        'title' => ('Big Features  Title'),
        'description' => ('Big Features description'),
        'render_callback' => 'render_acf_block_callback',
        'category' => 'happen-blocks',
        'icon' => 'block-default',
    ],
    'testimonials_grid_block' => [
        'name' => 'testimonials_grid_block',
        'title' => ('Testimonials Grid Block'),
        'description' => ('Testimonials Grid Block'),
        'render_callback' => 'render_acf_block_callback',
        'category' => 'happen-blocks',
        'icon' => 'block-default',
    ],
    'number-image-block' => [
    'name' => 'number-image-block',
    'title' => ('Number Image Block'),
    'description' => ('Number Image Block'),
    'render_callback' => 'render_acf_block_callback',
    'category' => 'happen-blocks',
    'icon' => 'block-default',
    ],
    'left-right-repeater-block' => [
        'name' => 'left-right-repeater-block',
        'title' => ('Left Right Repeater Block'),
        'description' => ('Left Right Repeater Block'),
        'render_callback' => 'render_acf_block_callback',
        'category' => 'happen-blocks',
        'icon' => 'block-default',
    ],
    'numbers_block' => [
    'name' => 'numbers_block',
    'title' => ('Numbers Block'),
    'description' => ('Numbers Block'),
    'render_callback' => 'render_acf_block_callback',
    'category' => 'happen-blocks',
    'icon' => 'block-default',
    ],
    'testimmonial_block' => [
    'name' => 'testimmonial_block',
    'title' => ('Testimmonial Block'),
    'description' => ('Testimmonial Block'),
    'render_callback' => 'render_acf_block_callback',
    'category' => 'happen-blocks',
    'icon' => 'block-default',
    ],
    'team_block' => [
    'name' => 'team_block',
    'title' => ('Team Block'),
    'description' => ('Team Block'),
    'render_callback' => 'render_acf_block_callback',
    'category' => 'happen-blocks',
    'icon' => 'block-default',
    ],
    'leadership_block' => [
        'name' => 'leadership_block',
        'title' => ('Leadership Block'),
        'description' => ('Leadership Block'),
        'render_callback' => 'render_acf_block_callback',
        'category' => 'happen-blocks',
        'icon' => 'block-default',
    ],
    'gallery-image-block' => [
        'name' => 'gallery-image-block',
        'title' => ('Gallery Image Block'),
        'description' => ('Gallery Image Block'),
        'render_callback' => 'render_acf_block_callback',
        'category' => 'happen-blocks',
        'icon' => 'block-default',
    ],
    'image-scroll-block' => [
        'name' => 'image-scroll-block',
        'title' => ('Image Scroll Block'),
        'description' => ('Image Scroll Block'),
        'render_callback' => 'render_acf_block_callback',
        'category' => 'happen-blocks',
        'icon' => 'block-default',
    ],
];
