<?php
$blocks = [
    'title_text_block' => [
        'name' => 'title_text_block',
        'title' => ('Title Text'),
        'description' => ('Description'),
        'render_callback' => 'render_acf_block_callback',
        'category' => 'happen-blocks',
        'icon' => 'block-default',
    ],
    'main_title_image' => [
        'name' => 'main_title_image',
        'title' => ('Main Title Image Block'),
        'description' => ('Description'),
        'render_callback' => 'render_acf_block_callback',
        'category' => 'happen-blocks',
        'icon' => 'block-default',
    ],
    'main_title_video' => [
        'name' => 'main_title_video',
        'title' => ('Main Title Video Block'),
        'description' => ('Description'),
        'render_callback' => 'render_acf_block_callback',
        'category' => 'happen-blocks',
        'icon' => 'block-default',
    ],
    'cols_info_block' => [
        'name' => 'cols_info_block',
        'title' => ('Cols Info Title'),
        'description' => ('Cols Info description'),
        'render_callback' => 'render_acf_block_callback',
        'category' => 'happen-blocks',
        'icon' => 'block-default',
    ],
    'signup_block' => [
        'name' => 'signup_block',
        'title' => ('Signup Block'),
        'description' => ('Signup description'),
        'render_callback' => 'render_acf_block_callback',
        'category' => 'happen-blocks',
        'icon' => 'block-default',
    ],
    'related_blog_posts_block' => [
        'name' => 'related_blog_posts_block',
        'title' => ('Related Blog Posts Title'),
        'description' => ('Related Blog Posts description'),
        'render_callback' => 'render_acf_block_callback',
        'category' => 'happen-blocks',
        'icon' => 'block-default',
    ],
    'big_features_block' => [
        'name' => 'big_features_block',
        'title' => ('Big Features  Title'),
        'description' => ('Big Features description'),
        'render_callback' => 'render_acf_block_callback',
        'category' => 'happen-blocks',
        'icon' => 'block-default',
    ],
    'number-image-block' => [
        'name' => 'number-image-block',
        'title' => ('Number Image Block'),
        'description' => ('Number Image Block'),
        'render_callback' => 'render_acf_block_callback',
        'category' => 'happen-blocks',
        'icon' => 'block-default',
    ],
    'number-gallery-block' => [
        'name' => 'number-gallery-block',
        'title' => ('Number Gallery Block'),
        'description' => ('Number Gallery Block'),
        'render_callback' => 'render_acf_block_callback',
        'category' => 'happen-blocks',
        'icon' => 'block-default',
    ],
    'left-right-repeater-block' => [
        'name' => 'left-right-repeater-block',
        'title' => ('Left Right Repeater Block'),
        'description' => ('Left Right Repeater Block'),
        'render_callback' => 'render_acf_block_callback',
        'category' => 'happen-blocks',
        'icon' => 'block-default',
    ],
    'numbers_block' => [
        'name' => 'numbers_block',
        'title' => ('Numbers Block'),
        'description' => ('Numbers Block'),
        'render_callback' => 'render_acf_block_callback',
        'category' => 'happen-blocks',
        'icon' => 'block-default',
    ],
    'testimmonial_block' => [
        'name' => 'testimmonial_block',
        'title' => ('Testimonial Block'),
        'description' => ('Testimonial Block'),
        'render_callback' => 'render_acf_block_callback',
        'category' => 'happen-blocks',
        'icon' => 'block-default',
    ],
    'team_block' => [
        'name' => 'team_block',
        'title' => ('Team Block'),
        'description' => ('Team Block'),
        'render_callback' => 'render_acf_block_callback',
        'category' => 'happen-blocks',
        'icon' => 'block-default',
    ],
    'leadership_block' => [
        'name' => 'leadership_block',
        'title' => ('Leadership Block'),
        'description' => ('Leadership Block'),
        'render_callback' => 'render_acf_block_callback',
        'category' => 'happen-blocks',
        'icon' => 'block-default',
    ],
    'gallery-image-block' => [
        'name' => 'gallery-image-block',
        'title' => ('Gallery Image Block'),
        'description' => ('Gallery Image Block'),
        'render_callback' => 'render_acf_block_callback',
        'category' => 'happen-blocks',
        'icon' => 'block-default',
    ],
    'image-scroll-block' => [
        'name' => 'image-scroll-block',
        'title' => ('Image Scroll Block'),
        'description' => ('Image Scroll Block'),
        'render_callback' => 'render_acf_block_callback',
        'category' => 'happen-blocks',
        'icon' => 'block-default',
    ],
    'image-slider-block' => [
        'name' => 'image-slider-block',
        'title' => ('Image Slider Block'),
        'description' => ('Image Slider Block'),
        'render_callback' => 'render_acf_block_callback',
        'category' => 'happen-blocks',
        'icon' => 'block-default',
    ],
];
